In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pickle
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, OneHotEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score, confusion_matrix
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import GaussianNB

### Разделим фичи по типам, отделим таргет и преобразуем его, разделим на тренировочную и тестирующую выборку

In [2]:
data_file = pd.read_csv('data.csv')

target = 'satisfaction'
drop_features = ['Unnamed: 0', 'id', 'Arrival Delay in Minutes']
numerical_features = ['Age', 'Flight Distance', 'Departure Delay in Minutes']
categorical_features_to_onehot = ['Gender', 'Customer Type', 'Type of Travel', 'Class']
categorical_features_other = [feat for feat in list(data_file.columns) if feat != target and feat not in numerical_features and feat not in drop_features and feat not in categorical_features_to_onehot]
 
X = data_file.drop(target,axis=1)
y = data_file[target]

enc = LabelEncoder()
y = enc.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, shuffle=True)

### Перпроцессинг данных

In [3]:
TransformColums = ColumnTransformer([
    ('Drop','drop',drop_features),
    ('Encoder', OneHotEncoder(), categorical_features_to_onehot),
    ('MinMax', MinMaxScaler(), [feature for feature in numerical_features if feature != 'Age']),
    ('StandartScaler', StandardScaler(), ['Age'])
], remainder='passthrough')



### Функция подчета метрик

In [4]:
def Metrics(model, X, y):
    y_pred = model.predict(X)
    print('Accuracy = ', accuracy_score(y, y_pred))
    print('Precision = ', precision_score(y, y_pred))
    print('Recall = ', recall_score(y, y_pred))
    print('ROC_AUC_score = ', roc_auc_score(y, y_pred))
    print('Confudion_Matrix =')
    print(confusion_matrix(y, y_pred))

### My KNN

In [6]:
from sklearn.metrics import euclidean_distances

class MyKNN(BaseEstimator, ClassifierMixin):
    def __init__(self, n_neighbors = 5):
        self.n_neighbors = n_neighbors
        
    def fit(self, X, y):
        self.fit_X = X
        self.fit_y = y
        return self
    
    
    def predict(self, X):
        distances = np.empty(X.shape[0])
        
        if len(X.shape) == 1:
            distances = euclidean_distances([X],self.fit_X)[0]
        else:
            distances = euclidean_distances(X,self.fit_X)
        distances_sorted = np.argsort(distances, axis=1)
        top_n = distances_sorted[:,:self.n_neighbors]
        
        answer = np.empty(X.shape[0])
        for i, elem in enumerate(top_n):
            local_ans = dict()
            for num in elem:
                if num in local_ans:
                    local_ans[self.fit_y[num]] += 1
                else:
                    local_ans[self.fit_y[num]] = 1
            max_count = max(local_ans, key = lambda k : local_ans.get(k))
            answer[i] = max_count

        return answer

In [7]:
knn_my_pipeline = Pipeline([
    ('Column Transform', TransformColums),
    ('knn', MyKNN())
])


knn_my = GridSearchCV(knn_my_pipeline,{'knn__n_neighbors':[1,3,5,7]})
knn_my.fit(X_train, y_train)

GridSearchCV(estimator=Pipeline(steps=[('Column Transform',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('Drop',
                                                                         'drop',
                                                                         ['Unnamed: '
                                                                          '0',
                                                                          'id',
                                                                          'Arrival '
                                                                          'Delay '
                                                                          'in '
                                                                          'Minutes']),
                                                                        ('Encoder',
                                                                         OneHotEncoder(),
                                                                         ['Gender',
                                                                          'Customer '
                                                                          'Type',
                                                                          'Type '
                                                                          'of '
                                                                          'Travel',
                                                                          'Class']),
                                                                        ('MinMax',
                                                                         MinMaxScaler(),
                                                                         ['Flight '
                                                                          'Distance',
                                                                          'Departure '
                                                                          'Delay '
                                                                          'in '
                                                                          'Minutes']),
                                                                        ('StandartScaler',
                                                                         StandardScaler(),
                                                                         ['Age'])])),
                                       ('knn', MyKNN())]),
             param_grid={'knn__n_neighbors': [1, 3, 5, 7]})

In [9]:
Metrics(knn_my, X_test, y_test)
pickle.dump(knn_my,open('models/knn_my.pkl','wb'))

Accuracy =  0.9236802848756075
Precision =  0.9188136951792053
Recall =  0.9014717447477811
ROC_AUC_score =  0.9208958050338232
Confudion_Matrix =
[[11171   709]
 [  877  8024]]


In [8]:
knn_my.best_params_

{'knn__n_neighbors': 1}

### KNN Sklearn

In [10]:
knn_sk_pipeline = Pipeline([
    ('Column Transform', TransformColums),
    ('knn', KNeighborsClassifier())
])

knn_sk = GridSearchCV(knn_sk_pipeline,{'knn__n_neighbors':[1,3,5,7]})
knn_sk.fit(X_train, y_train)

GridSearchCV(estimator=Pipeline(steps=[('Column Transform',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('Drop',
                                                                         'drop',
                                                                         ['Unnamed: '
                                                                          '0',
                                                                          'id',
                                                                          'Arrival '
                                                                          'Delay '
                                                                          'in '
                                                                          'Minutes']),
                                                                        ('Encoder',
                                                                         OneHotEncoder(),
                                                                         ['Gender',
                                                                          'Customer '
                                                                          'Type',
                                                                          'Type '
                                                                          'of '
                                                                          'Travel',
                                                                          'Class']),
                                                                        ('MinMax',
                                                                         MinMaxScaler(),
                                                                         ['Flight '
                                                                          'Distance',
                                                                          'Departure '
                                                                          'Delay '
                                                                          'in '
                                                                          'Minutes']),
                                                                        ('StandartScaler',
                                                                         StandardScaler(),
                                                                         ['Age'])])),
                                       ('knn', KNeighborsClassifier())]),
             param_grid={'knn__n_neighbors': [1, 3, 5, 7]})

In [23]:
Metrics(knn_sk, X_test, y_test)
pickle.dump(knn_sk,open('models/knn_sk.pkl','wb'))

Accuracy =  0.9334488234444925
Precision =  0.9470059530757559
Recall =  0.8972572439725724
ROC_AUC_score =  0.9292913700908948
Confudion_Matrix =
[[11285   454]
 [  929  8113]]


In [11]:
knn_sk.best_params_

{'knn__n_neighbors': 7}

### My LogisticRegression

In [30]:
class MyLogist(BaseEstimator, ClassifierMixin):
    def __init__(self, epochs = 100, learning_rate = 0.1):
        self.epochs = epochs
        self.learning_rate = learning_rate
        self.w = None
        
    def fit(self, X, y):
        if self.w is None:
            self.w = np.random.randn(X.shape[1] + 1)
            
        X = np.concatenate((np.ones((X.shape[0], 1)), X), axis=1)  # add bias as feature
        
        for i in range(self.epochs):
            self.w -= self.learning_rate*self._loss_grad(X,y)
        
        return self
        
    
    def predict(self, X):
        X = np.concatenate((np.ones((X.shape[0], 1)), X), axis=1)  # add bias as feature
        return self._sigmoid(np.dot(X, self.w)) > 0.5
    
    def _predict_no_bias(self, X):
        return self._sigmoid(np.dot(X, self.w)) > 0.5
    
    def _sigmoid(self, X):
        return 1.0 / (1.0 + np.exp(-X))
    
    def _loss_grad(self, X, y):
        return -((y - self._predict_no_bias(X)) @ X)

In [34]:
logit_my_pipeline = Pipeline([
    ('Column Transform', TransformColums),
    ('logit', MyLogist())
])

logit_my = GridSearchCV(logit_my_pipeline,{'logit__learning_rate':[0.1, 0.5],'logit__epochs':[100, 500, 1000]})
logit_my.fit(X_train, y_train)

/tmp/ipykernel_208/2768635174.py:27: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-X))
/tmp/ipykernel_208/2768635174.py:27: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-X))
/tmp/ipykernel_208/2768635174.py:27: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-X))
/tmp/ipykernel_208/2768635174.py:27: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-X))
/tmp/ipykernel_208/2768635174.py:27: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-X))
/tmp/ipykernel_208/2768635174.py:27: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-X))
/tmp/ipykernel_208/2768635174.py:27: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-X))
/tmp/ipykernel_208/2768635174.py:27: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-X))
/tmp/ipykernel_208/2768635174.py:27: RuntimeWarning: overflow encountered in exp

GridSearchCV(estimator=Pipeline(steps=[('Column Transform',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('Drop',
                                                                         'drop',
                                                                         ['Unnamed: '
                                                                          '0',
                                                                          'id',
                                                                          'Arrival '
                                                                          'Delay '
                                                                          'in '
                                                                          'Minutes']),
                                                                        ('Encoder',
                                                                         OneHotEncoder(),
                                                                         ['Gender',
                                                                          'Customer '
                                                                          'Type',
                                                                          'Type '
                                                                          'of '
                                                                          'Travel',
                                                                          'Class']),
                                                                        ('MinMax',
                                                                         MinMaxScaler(),
                                                                         ['Flight '
                                                                          'Distance',
                                                                          'Departure '
                                                                          'Delay '
                                                                          'in '
                                                                          'Minutes']),
                                                                        ('StandartScaler',
                                                                         StandardScaler(),
                                                                         ['Age'])])),
                                       ('logit', MyLogist())]),
             param_grid={'logit__epochs': [100, 500, 1000],
                         'logit__learning_rate': [0.1, 0.5]})

In [36]:
Metrics(logit_my, X_test, y_test)
pickle.dump(logit_my,open('models/logit_my.pkl','wb'))

Accuracy =  0.856984745681151
Precision =  0.8390172761947499
Recall =  0.8295252883762201
ROC_AUC_score =  0.8537766688374939
Confudion_Matrix =
[[10330  1435]
 [ 1537  7479]]


/tmp/ipykernel_208/2768635174.py:27: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-X))


### LogisticRegression Sklearn


In [25]:
logit_sk_pipeline = Pipeline([
    ('Column Transform', TransformColums),
    ('logit', LogisticRegression())
])

logit_sk = GridSearchCV(logit_sk_pipeline,{'logit__C':[10,1,0.1,0.01],'logit__max_iter':[500,1000,5000]})
logit_sk.fit(X_train, y_train)

GridSearchCV(estimator=Pipeline(steps=[('Column Transform',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('Drop',
                                                                         'drop',
                                                                         ['Unnamed: '
                                                                          '0',
                                                                          'id',
                                                                          'Arrival '
                                                                          'Delay '
                                                                          'in '
                                                                          'Minutes']),
                                                                        ('Encoder',
                                                                         OneHotEncoder(),
                                                                         ['Gender',
                                                                          'Customer '
                                                                          'Type',
                                                                          'Type '
                                                                          'of '
                                                                          'Travel',
                                                                          'Class']),
                                                                        ('MinMax',
                                                                         MinMaxScaler(),
                                                                         ['Flight '
                                                                          'Distance',
                                                                          'Departure '
                                                                          'Delay '
                                                                          'in '
                                                                          'Minutes']),
                                                                        ('StandartScaler',
                                                                         StandardScaler(),
                                                                         ['Age'])])),
                                       ('logit', LogisticRegression())]),
             param_grid={'logit__C': [10, 1, 0.1, 0.01],
                         'logit__max_iter': [500, 1000, 5000]})

In [26]:
Metrics(logit_sk, X_test, y_test)
pickle.dump(logit_sk,open('models/logit_sk.pkl','wb'))

Accuracy =  0.8740676579567874
Precision =  0.8660134442292355
Recall =  0.8406326034063261
ROC_AUC_score =  0.8702268562648805
Confudion_Matrix =
[[10563  1176]
 [ 1441  7601]]


### My SVM

In [273]:
class MySVM(BaseEstimator, ClassifierMixin):
    def __init__(self, epochs=1000, learning_rate=0.001, lambd = 0.01):
        self.epochs = epochs
        self.learning_rate = learning_rate
        self.lambd = lambd
        self.w = None
    
    def fit(self, X, y):
        if self.w is None:
            self.w = np.random.randn(X.shape[1] + 1)
            
        X = np.concatenate((np.ones((X.shape[0], 1)), X), axis=1)  # add bias as feature
        y = np.where(y == 0, -1, y)
        for i in range(self.epochs):
            self.w -= self.learning_rate*self._grad_loss(X, y)
        
    def predict(self, X):
        X = np.concatenate((np.ones((X.shape[0], 1)), X), axis=1)  # add bias as feature
        pred = np.dot(X,self.w)
        pred = np.where(pred >= 0, 1, 0)
        return pred
    
    def _grad_loss(self, X, y):
        loss = self.lambd*self.w
        for i, Xi in enumerate(X):
            if (y[i] * np.dot(self.w, Xi)) <= 0:
                loss -= y[i]*Xi
        return loss

In [277]:
svm_my_pipeline = Pipeline([
    ('Column Transform', TransformColums),
    ('SVM', MySVM())
])

svm_my = GridSearchCV(svm_my_pipeline,{'SVM__epochs':[100,500,1000], 'SVM__learning_rate':[0.1, 0.001, 0.00001]})
svm_my.fit(X_train, y_train)

KeyboardInterrupt: 

In [ ]:
Metrics(svm_my, X_test, y_test)

NotFittedError: This GridSearchCV instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

### SVM Sklearn

In [10]:
svm_sk_pipeline = Pipeline([
    ('Column Transform', TransformColums),
    ('SVM', LinearSVC())
])
svm_sk = GridSearchCV(svm_sk_pipeline,{'SVM__C':[10, 1, 0.1, 0.01], 'SVM__loss': ['hinge', 'squared_hinge']})
svm_sk.fit(X_train, y_train)

/home/pavel/ML_Lab1/ML/lib/python3.9/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/pavel/ML_Lab1/ML/lib/python3.9/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/pavel/ML_Lab1/ML/lib/python3.9/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/pavel/ML_Lab1/ML/lib/python3.9/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/pavel/ML_Lab1/ML/lib/python3.9/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/home/pavel/ML_Lab1/ML/lib/python3.9/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Li

GridSearchCV(estimator=Pipeline(steps=[('Column Transform',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('Drop',
                                                                         'drop',
                                                                         ['Unnamed: '
                                                                          '0',
                                                                          'id',
                                                                          'Arrival '
                                                                          'Delay '
                                                                          'in '
                                                                          'Minutes']),
                                                                        ('Encoder',
                                                                         OneHotEncoder(),
                                                                         ['Gender',
                                                                          'Customer '
                                                                          'Type',
                                                                          'Type '
                                                                          'of '
                                                                          'Travel',
                                                                          'Class']),
                                                                        ('MinMax',
                                                                         MinMaxScaler(),
                                                                         ['Flight '
                                                                          'Distance',
                                                                          'Departure '
                                                                          'Delay '
                                                                          'in '
                                                                          'Minutes']),
                                                                        ('StandartScaler',
                                                                         StandardScaler(),
                                                                         ['Age'])])),
                                       ('SVM', LinearSVC())]),
             param_grid={'SVM__C': [10, 1, 0.1, 0.01],
                         'SVM__loss': ['hinge', 'squared_hinge']})

In [27]:
Metrics(svm_sk, X_test, y_test)
pickle.dump(svm_sk,open('models/svm_sk.pkl','wb'))

Accuracy =  0.8761368557817237
Precision =  0.8763966480446927
Recall =  0.8327803583278036
ROC_AUC_score =  0.8711563432323914
Confudion_Matrix =
[[10677  1062]
 [ 1512  7530]]


### Naive bayes

In [14]:
nb_sk = Pipeline([
    ('Column Transform', TransformColums),
    ('NB', GaussianNB())
])
nb_sk.fit(X_train, y_train)

Pipeline(steps=[('Column Transform',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Drop', 'drop',
                                                  ['Unnamed: 0', 'id',
                                                   'Arrival Delay in Minutes']),
                                                 ('Encoder', OneHotEncoder(),
                                                  ['Gender', 'Customer Type',
                                                   'Type of Travel', 'Class']),
                                                 ('MinMax', MinMaxScaler(),
                                                  ['Flight Distance',
                                                   'Departure Delay in '
                                                   'Minutes']),
                                                 ('StandartScaler',
                                                  StandardScaler(),
                                                  ['Age'])])),
                ('NB', GaussianNB())])

In [15]:
Metrics(nb_sk, X_test, y_test)

Accuracy =  0.8526538665126798
Precision =  0.8372434017595308
Recall =  0.8209466932094669
ROC_AUC_score =  0.8490115525847999
Confudion_Matrix =
[[10296  1443]
 [ 1619  7423]]


In [22]:
pickle.dump(nb_sk,open('models/nb_sk.pkl','wb'))

<_io.BufferedWriter name='models/nb_sk.pkl'>